[package]
name = "beryl-client"
version.workspace = true
edition = "2021"

[dependencies]
# Workspace dependencies
beryl-common = { path = "../beryl-common" }
beryl-types = { path = "../beryl-types" }
beryl-proto = { path = "../beryl-proto" }

# RPC
tonic = { workspace = true }
prost = { workspace = true }

# Async runtime
tokio = { workspace = true }
futures = { workspace = true }

# Utilities
bytes = { workspace = true }
parking_lot = { workspace = true }

# Metrics
metrics = { workspace = true }

[dev-dependencies]
tokio-util = { workspace = true, features = ["compat"] }
tokio = { workspace = true, features = ["test-util"] }
tokio-stream = { version = "0.1", features = ["net"] }
