# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 Beryl Contributors

d /var/lib/beryl 0750 beryl beryl -
d /var/log/beryl 0750 beryl beryl -
f /var/log/beryl/metadata.log 0640 beryl beryl -
f /var/log/beryl/worker.log 0640 beryl beryl -
