[package]
name = "beryl-proto"
version.workspace = true
edition = "2024"

[dependencies]
beryl-types = { path = "../beryl-types" }
beryl-common = { path = "../beryl-common" }

prost = { workspace = true }
tonic = { workspace = true }
tonic-prost = { workspace = true }

[build-dependencies]
tonic-prost-build = { workspace = true }
