[package]
name = "beryl-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[[bin]]
name = "beryl"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
beryl-common = { path = "../beryl-common" }
clap = { workspace = true }

[dev-dependencies]
libc = { workspace = true }
tempfile = { workspace = true }
